### ISSUE TITLE
Can't install NuGet Package in Portable Class Library

### ISSUE THREAD

**Issue by prankard** [LosXamarinos/Xamarinos.AdMob.FormsPlugin#8]
When installing the NuGet in my PCL app, I get this error:

>>Attempting to gather dependency information for package 'Xamarinos.AdMob.FormsPlugin.1.0.8' with respect to project 'LifeBalance', targeting '.NETPortable,Version=v4.5,Profile=Profile259'
Attempting to resolve dependencies for package 'Xamarinos.AdMob.FormsPlugin.1.0.8' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Xamarinos.AdMob.FormsPlugin.1.0.8'
Resolved actions to install package 'Xamarinos.AdMob.FormsPlugin.1.0.8'
For adding package 'Xamarinos.AdMob.FormsPlugin.1.0.8' to project 'LifeBalance' that targets 'portable45-net45+win8+wp8+wpa81'.
Install failed. Rolling back...
Package 'Xamarinos.AdMob.FormsPlugin.1.0.8 : Xamarin.Forms [2.0.1.6505, )' does not exist in project 'LifeBalance'
Could not install package 'Xamarinos.AdMob.FormsPlugin 1.0.8'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I can however install the NuGet package in the main apps.

**Comment by realex82** [comment]
I've the same problem, how can i resolve it? 
Thanks
Alex

**Comment by prankard** [comment]
I couldn't clone and add the projects due to specific version of Forms
being required (outdated in mine, and in the wrong format), perhaps that is
the issue. But I'm not familiar with NuGet.

For a quick fix, copy these .cs files to your PCL project:
https://github.com/LosXamarinos/Xamarinos.AdMob.FormsPlugin/tree/master/PlugIn/Xamarinos.AdMob.Forms/Xamarinos.AdMob.Forms.FormsPlugin.Abstractions

Copy the one shared .cs file to each platform (you could create a shared
project if you wish which will make it easier to edit the file):
https://github.com/LosXamarinos/Xamarinos.AdMob.FormsPlugin/blob/master/PlugIn/Xamarinos.AdMob.Forms.Shared/CrossAdmobManager.cs

Copy each specific platform .cs files to the correct platform project:
Here it is for iOS:
https://github.com/LosXamarinos/Xamarinos.AdMob.FormsPlugin/tree/master/PlugIn/Xamarinos.AdMob.Forms/Xamarinos.AdMob.Forms.FormsPlugin.iOS

Then you should be good.

**Comment by realex82** [comment]
ok, thanks, i'll try this, but is too arcane as resolution. no add from developer  Alejandro  ?

**Comment by HarkDev** [comment]
I fixed it by doing the following:
- Forked the Repository
- Cloned it on my computer
- Opened the Xamarinos.AdMob.Forms.Abstractions.csproj on Notepad
- Edited the TargetFrameworkProfile tag from Profile78 to Profile111

I also commited it and asked the owner for a pull requst. Let's hope he accepts it, if not, you can just compile the project using this modifications or by cloning my fork https://github.com/HarkDev/Xamarinos.AdMob.FormsPlugin in which I also added an extra option to add test devices to the Banner renderer.

**Comment by nguyenthanhliemfc** [comment]
I have change me project to Profile 111. It's still not install

**Comment by brianjtools** [comment]
Too bad the NuGet package has not been updated.  It's very nice, easy to use plugin.  I built a test app that worked fine.  When I wanted to add it to my project though it wouldn't install because of the compatibility issue.  I tried building the updated version but there are many issues to solve upon install.  Just installing the .cs files as mentioned above introduced problems too.  I will try some other things or maybe another plugin.  BTW, one additional step was left out though VS will alert you to it in that the activity must  be added in the Android manifest like this:
`<activity android:name="com.google.android.gms.ads.AdActivity"
          android:theme="@android:style/Theme.Translucent"        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"/>`

**Comment by EmilAlipiev** [comment]
@prankard  shared project is only referenced on android project. why should we copy it to both projects? Interstitial ads implementation looks to me not correct. anybody could achieve it=

**Comment by EmilAlipiev** [comment]
I just implemented this package and works fine for interstiital https://github.com/ioliver85/Xamarin.Admob
